# Generated by Django 3.2.6 on 2021-08-31 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petroleum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='created_at',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
