# Generated by Django 3.2.6 on 2021-09-04 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transaction',
            table='transactions',
        ),
    ]
