# Generated by Django 3.2.6 on 2021-09-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lend', '0004_alter_transaction_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('credit', 'credit'), ('debit', 'debit')], max_length=50),
        ),
    ]
