# Generated by Django 3.2.6 on 2021-10-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Total_amount',
            new_name='total_amount',
        ),
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
